name = "nuxt-better-auth-demo"
main = ".output/server/index.mjs"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]
account_id = "ba6e044dfdaaffec3cac45e9feccd237"

[[d1_databases]]
binding = "DB"
database_name = "nuxt-better-auth-db"
database_id = "c57ea4c6-1f34-4933-904d-7dddd77510c1"

[observability]
enabled = true
